/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatsystem;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.font.TextAttribute;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Vihan
 */
public class ChatThreadMenu extends javax.swing.JFrame {

    /**
     * Creates new form ChatThreadMenu
     */
    
    private Medium medium;
    private String[] names;
    private CThread[] threadarr; 
    private User user;
    private CThread thread;
    
    
    public ChatThreadMenu(User user) {
        
        medium = new Medium();
        this.user = new User();
        this.thread = new CThread();
        this.user = user;
        initComponents();      
        this.setVisible(true);
        username.setText(user.getUsername());
        populateList();

        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sub_title = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        creatorLabel = new javax.swing.JLabel();
        threadNames = new javax.swing.JComboBox<>();
        creatorDisplay = new javax.swing.JTextField();
        selectThread = new javax.swing.JButton();
        addThread = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        removeThread = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lion Chat : Chat Threads");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images\\lion chat icon.png")));
        setResizable(false);

        sub_title.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        sub_title.setForeground(new java.awt.Color(153, 0, 0));
        sub_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sub_title.setText("Chat Threads");

        nameLabel.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(153, 0, 0));
        nameLabel.setText("Name         :");

        creatorLabel.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        creatorLabel.setForeground(new java.awt.Color(153, 0, 0));
        creatorLabel.setText("Created by   :");

        threadNames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        threadNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threadNamesActionPerformed(evt);
            }
        });

        creatorDisplay.setEditable(false);
        creatorDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatorDisplayActionPerformed(evt);
            }
        });

        selectThread.setText("Select Thread");
        selectThread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectThreadActionPerformed(evt);
            }
        });

        addThread.setText("Add Thread");
        addThread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addThreadActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(153, 0, 0));

        removeThread.setText("Remove Thread");
        removeThread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeThreadActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("User :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(sub_title))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(creatorLabel)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(creatorDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(threadNames, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectThread, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(addThread, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(removeThread)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sub_title, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threadNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creatorDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectThread)
                    .addComponent(addThread)
                    .addComponent(removeThread))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void threadNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threadNamesActionPerformed
       
        String name = threadNames.getSelectedItem().toString();
        
        if(name != null){
            String creator = medium.getThread(name).getCreator();
            creatorDisplay.setText(creator);
        }
        
        
    }//GEN-LAST:event_threadNamesActionPerformed

    private void creatorDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatorDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creatorDisplayActionPerformed

    private void addThreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addThreadActionPerformed
        new AddThread(user);
    }//GEN-LAST:event_addThreadActionPerformed

    private void selectThreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectThreadActionPerformed
        String name = threadNames.getSelectedItem().toString();
        boolean nameExist = !medium.nameValidity(name); // If nameValidity() method returns true,
                                                       // the thread does not exist anymore.
        
        if(name== null || name== ""){
            JOptionPane.showMessageDialog(null, "No thread is available. Please create a thread first", "No threads", JOptionPane.ERROR_MESSAGE);
        }
        
        else if (nameExist == false){
            JOptionPane.showMessageDialog(null, "The thread with the given name does not exist anymore. Please choose another thread.", "Thread does not exist", JOptionPane.ERROR_MESSAGE);
        }
        
        else{
            new ChatWindow(name, user);
        }
        
    }//GEN-LAST:event_selectThreadActionPerformed

    private void removeThreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeThreadActionPerformed
        
         
        String name = threadNames.getSelectedItem().toString();
        boolean nameExist = !medium.nameValidity(name);
        
        if(name == null || name.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Please select a thread");
        }
        
        else if (nameExist == false){
            JOptionPane.showMessageDialog(null, "The thread with the given name does not exist anymore. Please choose another thread.", "Thread does not exist", JOptionPane.ERROR_MESSAGE);
        }
        
        else{
            
            int choice = JOptionPane.showConfirmDialog(null, "Do you want to remove this thread?");
            
            if(choice == JOptionPane.YES_OPTION){
                medium.deleteThread(name);
                 populateList();
            }
            
        }
        
    }//GEN-LAST:event_removeThreadActionPerformed

    private void populateList(){
        
        threadNames.removeAll();
        names = medium.getThreads(user.getName());
        DefaultComboBoxModel dm = new DefaultComboBoxModel(names);
        threadNames.setModel(dm);
        // threadNames.setMaximumRowCount(names.length);
        
//        for (String name : names) {
//            threadNames.addItem(name);
//        }
        
    }
    

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
         //        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChatThreadMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChatThreadMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChatThreadMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChatThreadMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//          //new ChatThreadMenu();
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addThread;
    private javax.swing.JTextField creatorDisplay;
    private javax.swing.JLabel creatorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton removeThread;
    private javax.swing.JButton selectThread;
    private javax.swing.JLabel sub_title;
    private javax.swing.JComboBox<String> threadNames;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
