/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatsystem;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.font.TextAttribute;
import java.io.IOException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vihan
 */
public class ChatWindow extends javax.swing.JFrame {
     private Medium medium;
     private CThread thread;
     private User user;
     
    /**
     * Creates new form ChatWindow
     */
    public ChatWindow(String threadName, User user) {
        initComponents();
        medium = new Medium();
        this.user = new User();
        thread = medium.getThread(threadName);
        username.setText(user.getUsername());
        threadLabel.setText(thread.getName());
        creatorLabel.setText(thread.getCreator());
        chatDisplay.setText(thread.getContent());
        this.user = user;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        messageBox = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatDisplay = new javax.swing.JTextArea();
        chatWindow = new javax.swing.JLabel();
        detailBox = new javax.swing.JPanel();
        threadDisplay = new javax.swing.JLabel();
        creatorDisplay = new javax.swing.JLabel();
        threadDetails = new javax.swing.JLabel();
        threadLabel = new javax.swing.JLabel();
        creatorLabel = new javax.swing.JLabel();
        send = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lion Chat : Chat Window");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images\\lion chat icon.png")));
        setPreferredSize(new java.awt.Dimension(695, 750));
        setResizable(false);

        messageBox.setColumns(20);
        messageBox.setRows(5);
        jScrollPane3.setViewportView(messageBox);

        chatDisplay.setEditable(false);
        chatDisplay.setColumns(20);
        chatDisplay.setRows(5);
        jScrollPane1.setViewportView(chatDisplay);

        chatWindow.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        chatWindow.setForeground(new java.awt.Color(153, 0, 0));
        chatWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chatWindow.setText("Chat Window");

        detailBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));

        threadDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        threadDisplay.setForeground(new java.awt.Color(153, 0, 0));
        threadDisplay.setText("Thread  : ");

        creatorDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        creatorDisplay.setForeground(new java.awt.Color(153, 0, 0));
        creatorDisplay.setText("Creator :");

        threadDetails.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        threadDetails.setForeground(new java.awt.Color(153, 0, 0));
        threadDetails.setText("Thread Details");

        threadLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        threadLabel.setForeground(new java.awt.Color(153, 0, 0));

        creatorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        creatorLabel.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout detailBoxLayout = new javax.swing.GroupLayout(detailBox);
        detailBox.setLayout(detailBoxLayout);
        detailBoxLayout.setHorizontalGroup(
            detailBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailBoxLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(detailBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(threadDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(creatorDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(detailBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(threadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(creatorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(278, Short.MAX_VALUE))
            .addGroup(detailBoxLayout.createSequentialGroup()
                .addComponent(threadDetails)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        detailBoxLayout.setVerticalGroup(
            detailBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailBoxLayout.createSequentialGroup()
                .addComponent(threadDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(detailBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(threadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(threadDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creatorDisplay)
                    .addComponent(creatorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("User :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                            .addComponent(detailBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(chatWindow)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(chatWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        
       if(messageBox.getText().length() >0){
            
            String msg = messageBox.getText();
            String user = this.user.getUsername();
            String dateTime = medium.getDateTime();
            String display = user  + "[" + dateTime + "]" + " : " + medium.getMessage(msg) + "\n";
            
            if(chatDisplay.getText() == null){
                
                chatDisplay.setText(display);
                medium.sendContent(threadLabel.getText(), chatDisplay.getText());
                
            }
            else{
                chatDisplay.append(display);
                medium.sendContent(threadLabel.getText(), chatDisplay.getText());
            }
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Please type something", "No message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sendActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatDisplay;
    private javax.swing.JLabel chatWindow;
    private javax.swing.JLabel creatorDisplay;
    private javax.swing.JLabel creatorLabel;
    private javax.swing.JPanel detailBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea messageBox;
    private javax.swing.JButton send;
    private javax.swing.JLabel threadDetails;
    private javax.swing.JLabel threadDisplay;
    private javax.swing.JLabel threadLabel;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
