/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatsystem;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Vihan
 */
public class UserPanel extends javax.swing.JFrame {

    /**
     * Creates new form UserPanel
     */
    private String username;
    private String name;
    private User user;
    
    
    public UserPanel(User user) {
        
        this.user = new User();
        this.user = user;
        this.username = user.getUsername();
        this.name = user.getName();
        initComponents();
        usernameLabel.setText(username);
        nameLabel.setText(name);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chatWindow = new javax.swing.JLabel();
        detailBox = new javax.swing.JPanel();
        userdetails = new javax.swing.JLabel();
        nameDisplay = new javax.swing.JLabel();
        usernameDisplay = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        chatThreads = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lion Chat : User Panel");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images\\lion chat icon.png")));
        setResizable(false);

        chatWindow.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        chatWindow.setForeground(new java.awt.Color(153, 0, 0));
        chatWindow.setText("User Panel");

        detailBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        detailBox.setToolTipText("User Details");
        detailBox.setName("User Details"); // NOI18N

        userdetails.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        userdetails.setForeground(new java.awt.Color(153, 0, 0));
        userdetails.setText("User Details");

        nameDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameDisplay.setForeground(new java.awt.Color(153, 0, 0));
        nameDisplay.setText("Name       :");

        usernameDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameDisplay.setForeground(new java.awt.Color(153, 0, 0));
        usernameDisplay.setText("Username :");

        javax.swing.GroupLayout detailBoxLayout = new javax.swing.GroupLayout(detailBox);
        detailBox.setLayout(detailBoxLayout);
        detailBoxLayout.setHorizontalGroup(
            detailBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailBoxLayout.createSequentialGroup()
                .addComponent(userdetails)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(detailBoxLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(detailBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(nameDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(detailBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        detailBoxLayout.setVerticalGroup(
            detailBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailBoxLayout.createSequentialGroup()
                .addComponent(userdetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameDisplay)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 53, Short.MAX_VALUE))
        );

        chatThreads.setText("View chat threads");
        chatThreads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatThreadsActionPerformed(evt);
            }
        });

        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chatWindow)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chatThreads)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout))
                    .addComponent(detailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(detailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatThreads)
                    .addComponent(logout))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chatThreadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatThreadsActionPerformed
        ChatThreadMenu ctm = new ChatThreadMenu(user);
    }//GEN-LAST:event_chatThreadsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?");
        
        if(choice == JOptionPane.YES_OPTION){
            new Main();
            this.dispose();
            JOptionPane.showMessageDialog(null, "Log out successful");
            
        }
    
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
         //        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chatThreads;
    private javax.swing.JLabel chatWindow;
    private javax.swing.JPanel detailBox;
    private javax.swing.JButton logout;
    private javax.swing.JLabel nameDisplay;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel userdetails;
    private javax.swing.JLabel usernameDisplay;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
